spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db
    username: root
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show_sql: true